import { db } from "../src/lib/db";
import { foodBanks, type HoursType } from "../src/lib/schema";

type SeedFoodBank = typeof foodBanks.$inferInsert;

const seedData: SeedFoodBank[] = [
  {
    name: "Sacramento Food Bank & Family Services",
    address: "1951 Bell Ave",
    city: "Sacramento",
    state: "CA",
    zipCode: "95838",
    latitude: 38.6494,
    longitude: -121.4426,
    phone: "(916) 456-1980",
    website: "https://www.sacramentofoodbank.org/",
    description:
      "Distribution center providing emergency groceries, produce, and family services for Sacramento County residents.",
    services: ["Emergency Groceries", "CalFresh Assistance", "Family Services"],
    hours: {
      Monday: { open: "8:00 AM", close: "4:00 PM" },
      Tuesday: { open: "8:00 AM", close: "4:00 PM" },
      Wednesday: { open: "8:00 AM", close: "4:00 PM" },
      Thursday: { open: "8:00 AM", close: "4:00 PM" },
      Friday: { open: "8:00 AM", close: "4:00 PM" },
      Saturday: { open: "8:00 AM", close: "12:00 PM" },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "River City Food Bank – Midtown",
    address: "1800 28th St",
    city: "Sacramento",
    state: "CA",
    zipCode: "95816",
    latitude: 38.5711,
    longitude: -121.4732,
    phone: "(916) 446-2627",
    website: "https://rivercityfoodbank.org/",
    description:
      "Midtown location offering daily emergency food distribution with produce, proteins, and pantry staples.",
    services: ["Emergency Groceries", "Nutrition Education"],
    hours: {
      Monday: { open: "10:30 AM", close: "1:30 PM" },
      Tuesday: { open: "4:00 PM", close: "7:00 PM" },
      Wednesday: { open: "10:30 AM", close: "1:30 PM" },
      Thursday: { open: "10:30 AM", close: "1:30 PM" },
      Friday: { open: "10:30 AM", close: "1:30 PM" },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "River City Food Bank – Arden",
    address: "2300 Edison Ave",
    city: "Sacramento",
    state: "CA",
    zipCode: "95821",
    latitude: 38.6207,
    longitude: -121.4099,
    phone: "(916) 446-2627",
    website: "https://rivercityfoodbank.org/",
    description:
      "Arden-Arcade campus with drive-through distribution and nutrition classes.",
    services: ["Drive-Through Pantry", "CalFresh Assistance"],
    hours: {
      Monday: { open: "Closed", close: "Closed", closed: true },
      Tuesday: { open: "10:30 AM", close: "1:30 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "4:00 PM", close: "7:00 PM" },
      Friday: { open: "10:30 AM", close: "1:30 PM" },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Elk Grove Food Bank Services",
    address: "9820 Dino Dr",
    city: "Elk Grove",
    state: "CA",
    zipCode: "95624",
    latitude: 38.4188,
    longitude: -121.392,
    phone: "(916) 685-8453",
    website: "https://elkgrovefoodbank.org/",
    description:
      "County partner serving Elk Grove with emergency food, mobile pantry, and senior boxes.",
    services: ["Emergency Groceries", "Senior Delivery", "Mobile Pantry"],
    hours: {
      Monday: { open: "9:00 AM", close: "3:00 PM" },
      Tuesday: { open: "9:00 AM", close: "3:00 PM" },
      Wednesday: { open: "9:00 AM", close: "3:00 PM" },
      Thursday: { open: "9:00 AM", close: "3:00 PM" },
      Friday: { open: "9:00 AM", close: "3:00 PM" },
      Saturday: { open: "9:00 AM", close: "12:00 PM" },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Cordova Community Food Locker",
    address: "10425 Folsom Blvd",
    city: "Rancho Cordova",
    state: "CA",
    zipCode: "95670",
    latitude: 38.5899,
    longitude: -121.2827,
    phone: "(916) 364-8973",
    website: "https://www.cordovafoodlocker.org/",
    description:
      "Volunteer-run pantry serving Rancho Cordova residents with weekly groceries.",
    services: ["Emergency Groceries", "USDA Commodities"],
    hours: {
      Monday: { open: "Closed", close: "Closed", closed: true },
      Tuesday: { open: "9:00 AM", close: "1:00 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "9:00 AM", close: "1:00 PM" },
      Friday: { open: "Closed", close: "Closed", closed: true },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "South Sacramento Interfaith Partnership Food Closet",
    address: "5625 24th St",
    city: "Sacramento",
    state: "CA",
    zipCode: "95822",
    latitude: 38.5201,
    longitude: -121.4883,
    phone: "(916) 428-5290",
    website: "https://www.ssipfoodcloset.org/",
    description:
      "Community-supported food closet serving Oak Park, Hollywood Park, and nearby neighborhoods.",
    services: ["Emergency Groceries", "Community Referrals"],
    hours: {
      Monday: { open: "9:00 AM", close: "11:30 AM" },
      Tuesday: { open: "Closed", close: "Closed", closed: true },
      Wednesday: { open: "9:00 AM", close: "11:30 AM" },
      Thursday: { open: "Closed", close: "Closed", closed: true },
      Friday: { open: "9:00 AM", close: "11:30 AM" },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "North Highlands Christian Food Ministry",
    address: "6125 Watt Ave",
    city: "North Highlands",
    state: "CA",
    zipCode: "95660",
    latitude: 38.677,
    longitude: -121.3894,
    phone: "(916) 955-1010",
    website: "https://www.christianfoodministry.org/",
    description:
      "Faith-based pantry providing emergency food to North Highlands, Antelope, and Foothill Farms residents.",
    services: ["Emergency Groceries", "USDA Commodities"],
    hours: {
      Monday: { open: "9:00 AM", close: "1:00 PM" },
      Tuesday: { open: "9:00 AM", close: "1:00 PM" },
      Wednesday: { open: "9:00 AM", close: "1:00 PM" },
      Thursday: { open: "9:00 AM", close: "1:00 PM" },
      Friday: { open: "9:00 AM", close: "1:00 PM" },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Orangevale-Fair Oaks Food Bank",
    address: "6483 Main Ave",
    city: "Orangevale",
    state: "CA",
    zipCode: "95662",
    latitude: 38.6786,
    longitude: -121.2266,
    phone: "(916) 304-3503",
    website: "https://orangevalefoodbank.org/",
    description:
      "Regional food bank offering drive-through distribution, mobile pantry, and community gardens.",
    services: ["Drive-Through Pantry", "Mobile Pantry", "Community Garden"],
    hours: {
      Monday: { open: "Closed", close: "Closed", closed: true },
      Tuesday: { open: "9:00 AM", close: "1:00 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "4:00 PM", close: "7:00 PM" },
      Friday: { open: "9:00 AM", close: "12:00 PM" },
      Saturday: { open: "9:00 AM", close: "12:00 PM" },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Sunrise Christian Food Ministry",
    address: "5901 Sunrise Vista Dr",
    city: "Citrus Heights",
    state: "CA",
    zipCode: "95610",
    latitude: 38.6665,
    longitude: -121.261,
    phone: "(916) 965-5431",
    website: "https://www.sunrisechristianfoodministry.org/",
    description:
      "Emergency food closet serving Citrus Heights, Fair Oaks, Orangevale, and surrounding communities.",
    services: ["Emergency Groceries", "Medication Assistance"],
    hours: {
      Monday: { open: "Closed", close: "Closed", closed: true },
      Tuesday: { open: "9:00 AM", close: "1:00 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "9:00 AM", close: "1:00 PM" },
      Friday: { open: "Closed", close: "Closed", closed: true },
      Saturday: { open: "9:00 AM", close: "1:00 PM" },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Twin Lakes Food Bank",
    address: "327 Montrose Dr",
    city: "Folsom",
    state: "CA",
    zipCode: "95630",
    latitude: 38.6773,
    longitude: -121.1689,
    phone: "(916) 985-6232",
    website: "https://twinlakesfoodbank.org/",
    description:
      "Serving Folsom and El Dorado Hills with weekly groceries, fresh produce, and senior boxes.",
    services: ["Emergency Groceries", "Senior Boxes", "Holiday Meals"],
    hours: {
      Monday: { open: "9:00 AM", close: "12:00 PM" },
      Tuesday: { open: "9:00 AM", close: "12:00 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "9:00 AM", close: "12:00 PM" },
      Friday: { open: "Closed", close: "Closed", closed: true },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
  {
    name: "Oak Park Community Food Bank",
    address: "3425 Martin Luther King Jr Blvd",
    city: "Sacramento",
    state: "CA",
    zipCode: "95817",
    latitude: 38.5369,
    longitude: -121.4586,
    phone: "(916) 477-1633",
    website: "https://www.oakparkcommunitycenter.com/",
    description:
      "Neighborhood food bank providing weekly groceries and community resources in Oak Park.",
    services: ["Emergency Groceries", "Community Resources"],
    hours: {
      Monday: { open: "Closed", close: "Closed", closed: true },
      Tuesday: { open: "10:00 AM", close: "1:00 PM" },
      Wednesday: { open: "Closed", close: "Closed", closed: true },
      Thursday: { open: "10:00 AM", close: "1:00 PM" },
      Friday: { open: "Closed", close: "Closed", closed: true },
      Saturday: { open: "Closed", close: "Closed", closed: true },
      Sunday: { open: "Closed", close: "Closed", closed: true },
    },
  },
];

async function seed() {
  try {
    await db.insert(foodBanks).values(seedData);
    console.log("✅ Seeded food banks successfully.");
  } catch (error) {
    console.error("❌ Failed to seed food banks", error);
    process.exit(1);
  }
}

seed().then(() => process.exit(0));
